on:
  workflow_dispatch:
  push:
    branches: main
  schedule:
    - cron: '0 0 * * 0'  # every Sunday at midnight


name: Render and Publish to Netlify

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install missing system dependencies
        if: runner.os == 'Linux'
        run: sudo apt-get update && sudo apt-get install build-essentials

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: false

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
      
      - name: Install R dependencies
        uses: r-lib/actions/setup-renv@v2 # r packages
      
      - name: Publish to Netlify (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: netlify
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        
